### ISSUE TITLE
a bug in hamt traversal example

### ISSUE THREAD

**Issue by lidel** [ipld/explore.ipld.io#122]
To Reproduce:
1. Open https://explore.ipld.io/#/explore/bafybeiaysi4s6lnjev27ln5icwm6tueaw2vdykrtjkwiphwekaywqhcjze/1D_exceptions
2. Click on  ![2023-07-13_19-25_1](https://github.com/ipld/explore.ipld.io/assets/157609/79d647c6-71ab-4af3-aedd-31f473a20893)
`7 0CA%2fMonitor_%2f%2f` → nothing changes, same node is shown, header shows broken(?) breadcrumb:  
![2023-07-13_19-25](https://github.com/ipld/explore.ipld.io/assets/157609/f053144c-8678-4260-9be2-bac2bf37d834) and the same node is shown
3. Click on ![2023-07-13_19-25_1](https://github.com/ipld/explore.ipld.io/assets/157609/79d647c6-71ab-4af3-aedd-31f473a20893) again → nothing happens

Expected:
Click on  ![2023-07-13_19-25_1](https://github.com/ipld/explore.ipld.io/assets/157609/79d647c6-71ab-4af3-aedd-31f473a20893) should step into  its CID

**Comment by SgtPooki** [comment]
Thanks @lidel , I was able to reproduce and put this in our planned backlog of items

**Comment by SgtPooki** [comment]
re-opening cause we have to deploy the new explorer components here.
