### ISSUE TITLE
ethereum blocks displayed incorrectly

### ISSUE THREAD

**Issue by whyrusleeping** [ipld/explore.ipld.io#32]
This looks like its just displaying the underlying javascript object: https://explore.ipld.io/#/explore/z43AaGEvwdfzjrCZ3Sq7DKxdDHrwoaPQDtqF4jfdkNEVTiqGVFW

It should be showing the ipld object, not the javascript object that backs the ipld object

**Comment by alanshaw** [comment]
The CLI explorer does this also. The output of `toJSON` might be more useful here?

**Comment by olizilla** [comment]
See: https://github.com/ipld/js-ipld-ethereum/issues/25

**Comment by olizilla** [comment]
> - `ipld.get(cid)` returns the wrong thing (ipld/js-ipld#142)
> - js-ipld-ethereum (and other resolvers) return the wrong thing (or fail!) with `resolver.resolve(cid, '/', callback)` (ipld/interface-ipld-format#34)
> - Some questions about the format of links in particular, but I think this is less relevant since IPLD Explorer is already handling both styles we are discussing unifying (ipld/ipld#44)

https://github.com/ipld/js-ipld-ethereum/issues/25#issuecomment-411816876

**Comment by lidel** [comment]
Not relevant since https://github.com/ipfs/ipld-explorer-components/pull/360
