### ISSUE TITLE
Update website  to latest js-ipfs and ipld-explorer-components

### ISSUE THREAD

**Issue by lidel** [ipld/explore.ipld.io#69]
- [ ] update  [ipld-explorer-components]()https://github.com/ipfs/ipld-explorer-components) to  the latest JS APIs
  - caveat: it has to work with both js-ipfs embeddded on explore.ipld.io AND go-ipfs via js-ipfs-http-client in ipfs-webui 
- [ ] update this repo to the latest js-ipfs 
  - [x] ensure we use 4 preload nodes instead of only 2 (#72)
  -  enabling best-effort  webrtc  like we did in https://github.com/ipfs-shipyard/ipfs-share-files/pull/121 could improve link sharing between browsers

**Comment by alanshaw** [comment]
Also needs an update to bootstrap peers:

<img width="946" alt="Screenshot 2021-07-28 at 10 02 34" src="https://user-images.githubusercontent.com/152863/127296695-553ca437-9cf4-46c1-ab78-f13644eaa73a.png">

**Comment by achingbrain** [comment]
> update to latest js-ipfs

The latest js-ipfs supports the new multiformats stack, but some codecs haven't been implemented yet (e.g. `ipld-bitcoin`, `ipld-ethereum`, `ipld-git` and `ipld-zcash` at least) - these will need to be wrapped in the [ipld-format-to-blockcodec](https://www.npmjs.com/package/ipld-format-to-blockcodec) module if we wish to continue supporting them in the explorer.

**Comment by lidel** [comment]
fwiw this should not be a blocker –  I suggested removing those fringe formats from example list – those are not supported out of the box in js-ipfs anymore, and adding `dag-cbor` / `dag-json`  ones instead is way more valuable for ecosystem: https://github.com/ipld/explore.ipld.io/issues/62#issuecomment-812567421 

Added to the maintenance board.

**Comment by achingbrain** [comment]
> those are not supported out of the box in js-ipfs anymore

It's possible to configure them fairly easily, see [examples/traverse-ipld-graphs/eth.js](https://github.com/ipfs/js-ipfs/blob/master/examples/traverse-ipld-graphs/eth.js) and [examples/traverse-ipld-graphs/git.js](https://github.com/ipfs/js-ipfs/blob/master/examples/traverse-ipld-graphs/git.js) for how.

**Comment by BigLep** [comment]
Next steps per 2021-07-30 discussion:
1. When this does get touched, we need to make sure we're able to stay up-to-date with latest ipld used in js-ipfs.  We should have CI running that catches issues sooner while attempting to use the latest versions.  
2. We don't know if a tribute will be able to take this during their tribute week.
3. It may make sense to build this application from scratch and hire it out.  The first step here would be w3dt Stewards to write a Minimal Project Proposal describing the problem/candidate.

**Comment by BigLep** [comment]
Note that on 2021-09-21 we had another outage that was resolved with https://github.com/ipld/explore.ipld.io/pull/72

**Comment by lidel** [comment]
Additional context about how IPLD Explorer consumes libraries and data (useful for onboarding when picking up the upgrade tasks):

> There is a deeper problem and nuance around ownership and dogfooding in IPLD Explorer.
> IIRC IPLD Explorer reads raw blocks via `ipfs.block.get` and processes them in the browser using [js-ipld](https://github.com/ipld/js-ipld#readme) (thse days deprecated in favor of [js-multiformats](https://github.com/multiformats/js-multiformats)).
> 
> I believe the app uses IPLD libs directly because `ipfs.dag.*` was not enough at the time. Last time I checked `ipfs.dag.*` was still not ready (API exposed by js-ipfs and go-ipfs+js-ipfs-http-client had different behaviors).
>
> While tempting to "do use IPLD end-to-end" here, switching IPLD Explorer to `ipfs.dag.*` is much bigger task because it requires cleanup and unification of `ipfs.dag.*` in go-ipfs and js-ipfs* and I am not sure if that should be in scope of this app (we have [interop](https://github.com/ipfs/interop/) test suite for things like this).
> 
> Keeping the existing approach of fetching raw blocks and processing them via IPLD lib directly is probably the safest path forward, as it is immune to `ipfs.dag.*` discrepancies and makes it work the same no matter which backend is used.
>
> In my mind, descoping `ipfs.dag.*` from IPLD explorer is a feature, not a bug: this way we could create and run E2E tests for explore.ipld.io in CI of [js-multiformats](https://github.com/multiformats/js-multiformats) library,  providing IPLD team with instant feedback about breaking changes and painful refactors.

**Comment by lidel** [comment]
This happened sround https://github.com/ipld/explore.ipld.io/pull/73
