### ISSUE TITLE
Truncated CIDs

### ISSUE THREAD

**Issue by achingbrain** [ipld/explore.ipld.io#71]
**Describe the bug**

When scanning through a list of stringified CIDs, often the last few characters are the most useful.

The dag explorer truncates the CIDs despite having loads of space available to display them.

**To Reproduce**
1. Load a CID
2. Look at the list of links
3. Wonder what the last few characters are

**Expected behavior**

It'd be really helpful to be able to see the whole CID.

**Screenshots**

![image](https://user-images.githubusercontent.com/665810/126031301-1f25666a-ddbe-4aa0-bc85-ca195da43685.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser Chrome
 - Version 91

**Comment by davidd8** [comment]
I have a fix for this issue, and it requires a change in https://github.com/ipfs/ipld-explorer-components @lidel can you give me access to both repos so I can add a PR?

**Comment by davidd8** [comment]
Forked the fix in https://github.com/ipfs/ipld-explorer-components/pull/303

**Comment by lidel** [comment]
@davidd8 i released `ipld-explorer-components@2.0.3` with your fix, mind opening a PR that bumps the dependency in this repo to that version?

**Comment by davidd8** [comment]
@lidel created https://github.com/ipld/explore.ipld.io/pull/73
