### ISSUE TITLE
Remove Ethereum example?

### ISSUE THREAD

**Issue by lidel** [ipld/explore.ipld.io#74]
I believe this example makes more harm than good. 
go-ipfs 0.12.0  does not ship with ethereum codec, and when someone tries to open/traverse the DAG it in ANY of our existing IPFS tooling, they get an error:

```console
$ ipfs refs -r bagiacgzah24drzou2jlkixpblbgbg6nxfrasoklzttzoht5hixhxz3rlncyq 
Error: could not choose a decoder: no decoder registered for multicodec code 144 (0x90)
```

My take: examples should be _educational_, not confusion-inducing. 

Ok to remove it?

cc @mikeal @warpfork @mvdan

**Comment by mvdan** [comment]
Sounds reasonable to me :) If we lose part of the message that IPLD is interoperable by removing one good example, perhaps we can find another good example that does work on go-ipfs by default.

**Comment by SgtPooki** [comment]
Is this something we should remove without a replacement? or is there a suggestion for a replacement we could use?

**Comment by lidel** [comment]
Remove it, nobody cared about this enough to fix it for more multiple years, and makes more harm than good.
Child blocks are not provided by anyone, spinner forever, looks broken → makes IPFS/IPLD look bad.

**Comment by SgtPooki** [comment]
related: https://github.com/ipfs/js-ipfs/issues/1453

**Comment by i-norden** [comment]
Linking this comment here: https://github.com/ipfs/ipld-explorer-components/pull/360/files/09ab5e813ff38395528ae3ca798e0d7b1e1dea70#r1218762651

All that said I have no strong feelings about removing/not removing the ethereum examples here, just providing some context and potential options.

**Comment by SgtPooki** [comment]
I was just about to add a link to your comment, thanks for adding that.

I think until we have a good plan forward for ipld-ethereum examples, or a need for users of explore.ipld.io to have ethereum codecs, we should put this on the back burner.
